export const Types = {
  POC_GET_REQUEST: 'poc/POC_GET_REQUEST',
  POC_GET_SUCCESS: 'poc/POC_GET_SUCCESS',
  POC_GET_FAILURE: 'poc/POC_GET_FAILURE',
  PRODUCTS_GET_REQUEST: 'products/PRODUCTS_GET_REQUEST',
  PRODUCTS_GET_SUCCESS: 'products/PRODUCTS_GET_SUCCESS',
  PRODUCTS_GET_FAILURE: 'products/PRODUCTS_GET_FAILURE',
  CATEGORIES_GET_REQUEST: 'products/CATEGORIES_GET_REQUEST',
  CATEGORIES_GET_SUCCESS: 'products/CATEGORIES_GET_SUCCESS',
  CATEGORIES_GET_FAILURE: 'products/CATEGORIES_GET_FAILURE'
};
